### ISSUE TITLE
Json object issue

### ISSUE THREAD

**Issue by zeflex514** [JevinJ/Bittrex-Notify#3]
`root@vmi135230:~/bittrex_notify/Bittrex-Notify-master/src# python3 main.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1536, in __call__
    return self.func(*args)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 585, in callit
    func(*args)
  File "main.py", line 420, in fast_timer_update
    self.update_ticker_data('r')
  File "main.py", line 369, in update_ticker_data
    self.r_ticker_data = fasttick.heartbeat()
  File "/root/bittrex_notify/Bittrex-Notify-master/src/fasttick.py", line 47, in heartbeat
    data = json.loads(page)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

`

Do you face to same issue sometimes or do I miss something ?

**Comment by JevinJ** [comment]
Probably way late for this as I've been MIA for a while. This is fixed now in the latest push.
