### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by yasirjani** [JevinJ/Bittrex-Notify#4]
@JevinJ Hi, The bot was functionally good but suddenly today it gives me an error. I update everything but still the following errors, Please, If possible solve the errors or give any suggestion to fix this problem thanks a lot for great bot. 
______________________________________________________________________________

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 745, in callit
    func(*args)
  File "G:\Bot\Bittrex\noti2\src\main.py", line 275, in fast_timer_update
    self.r_ticker_data_update()
  File "G:\Bot\Bittrex\noti2\src\main.py", line 219, in r_ticker_data_update
    self.r_ticker_data = fasttick.heartbeat()
  File "G:\Bot\Bittrex\noti2\src\fasttick.py", line 43, in heartbeat
    if i['Market']['BaseCurrency'] == 'BTC' and last_price >= 0.00001000 and last_vol >= 350:
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 745, in callit
    func(*args)
  File "G:\Bot\Bittrex\noti2\src\main.py", line 260, in slow_timer_update
    self.m_ticker_data_update()
  File "G:\Bot\Bittrex\noti2\src\main.py", line 213, in m_ticker_data_update
    self.m_ticker_data = slowtick.heartbeat()
  File "G:\Bot\Bittrex\noti2\src\slowtick.py", line 43, in heartbeat
    if i['Market']['BaseCurrency'] == 'BTC' and last_price >= 0.00001000 and last_vol >= 350:
TypeError: '>=' not supported between instances of 'NoneType' and 'float'

**Comment by JevinJ** [comment]
@yasirjani Hi, I'm seeing function calls and variables that are changed in the latest version in your traceback. This shouldn't happen anymore in the /src/ folder I pushed on Jan 17, try deleting your version of /src/ and put the new one in its place. Let me know if you still have an issue.
